version: '3.8'

services:
  airflow-webserver:
    image: apache/airflow:2.9.0
    command: webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_processor.py:/opt/airflow/spark_processor.py
      - ./metabaseduck:/opt/metabaseduck
      - /home/user/jupyter/minsait/dados:/opt/airflow/minsait/dados  # Mapeia os dados do Jupyter
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.9.0
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_processor.py:/opt/airflow/spark_processor.py
      - ./metabaseduck:/opt/metabaseduck
      - /home/user/jupyter/minsait/dados:/opt/airflow/minsait/dados  # Mapeia os dados do Jupyter
    depends_on:
      - postgres

  airflow-init:
    image: apache/airflow:2.9.0
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    build:
      context: .
      dockerfile: Dockerfile.metabase
    ports:
      - "3001:3000"
    volumes:
      - ./metabaseduck:/data

volumes:
  postgres_data:
